export const BRICKLINK_CONSUMER_KEY = process.env.BRICKLINK_CONSUMER_KEY
export const BRICKLINK_CONSUMER_SECRET = process.env.BRICKLINK_CONSUMER_SECRET
export const BRICKLINK_TOKEN_VALUE = process.env.BRICKLINK_TOKEN_VALUE
export const BRICKLINK_TOKEN_SECRET = process.env.BRICKLINK_TOKEN_SECRET
export const BRICKSET_API_KEY = process.env.BRICKSET_API_KEY
export const BRICKSET_API_URL = process.env.BRICKSET_API_URL
export const PORT = process.env.PORT || 5002
